name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    tests:
        name: tests and quality
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_USER: ${{ secrets.DB_USER }}
                    POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
                    POSTGRES_DB: ina_zaoui_test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # checkout v4.0
            - name: Setup PHP 8.4
              uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # setup-php v2.36.0
              with:
                  php-version: '8.4'
                  extensions: pdo_pgsql, intl

            - name: Install dependencies
              run: composer install

            - name: Setup database
              env:
                  DATABASE_URL: postgresql://symfony:symfony@127.0.0.1:5432/ina_zaoui?serverVersion=16&charset=utf8
              run: |
                  php bin/console doctrine:migrations:migrate --env=test --no-interaction
                  php bin/console doctrine:fixtures:load --env=test --no-interaction

            - name: Run PHPStan
              run: php vendor/bin/phpstan analyze

            - name: Run tests
              env:
                  DATABASE_URL: postgresql://symfony:symfony@127.0.0.1:5432/ina_zaoui?serverVersion=16&charset=utf8
              run: php bin/phpunit --coverage-clover clover.xml

            - name: Coverage Check
              uses: docker://ghcr.io/ericsizemore/phpunit-coverage-check-action
              with:
                clover_file: 'clover.xml'
                threshold: 70
